/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
"use strict";

systemDictionary = {
	"cron_scenes adapter settings": {
		en: "Adapter settings for cron_scenes",
		de: "Adaptereinstellungen für cron_scenes",
		ru: "Настройки адаптера для cron_scenes",
		pt: "Configurações do adaptador para cron_scenes",
		nl: "Adapterinstellingen voor cron_scenes",
		fr: "Paramètres d'adaptateur pour cron_scenes",
		it: "Impostazioni dell'adattatore per cron_scenes",
		es: "Ajustes del adaptador para cron_scenes",
		pl: "Ustawienia adaptera dla cron_scenes",
		uk: "Налаштування адаптера для cron_scenes",
		"zh-cn": "cron_scenes的适配器设置",
	},
	general_settings: {
		en: "General Settings",
		de: "Allgemeine Einstellungen",
		ru: "Общие настройки",
		pt: "Configurações Gerais",
		nl: "Algemene Instellingen",
		fr: "Paramètres Généraux",
		it: "Impostazioni Generali",
		es: "Configuración General",
		pl: "Ustawienia Ogólne",
		uk: "Загальні налаштування",
		"zh-cn": "常规设置",
	},
	job_settings: {
		en: "Job Settings",
		de: "Job-Einstellungen",
		ru: "Настройки заданий",
		pt: "Configurações de Trabalho",
		nl: "Job Instellingen",
		fr: "Paramètres des Tâches",
		it: "Impostazioni Lavoro",
		es: "Configuración de Trabajos",
		pl: "Ustawienia Zadań",
		uk: "Налаштування завдань",
		"zh-cn": "作业设置",
	},
	cronFolder: {
		en: "Jobs Folder Path",
		de: "Jobs-Ordner-Pfad",
		ru: "Путь к папке заданий",
		pt: "Caminho da Pasta de Trabalhos",
		nl: "Jobs Map Pad",
		fr: "Chemin du Dossier des Tâches",
		it: "Percorso Cartella Lavori",
		es: "Ruta de Carpeta de Trabajos",
		pl: "Ścieżka Folderu Zadań",
		uk: "Шлях до папки завдань",
		"zh-cn": "作业文件夹路径",
	},
	cronFolder_help: {
		en: "Custom path for storing cron job configurations (leave empty for default)",
		de: "Benutzerdefinierter Pfad für Cron-Job-Konfigurationen (leer lassen für Standard)",
		ru: "Пользовательский путь для хранения конфигураций cron-заданий",
		pt: "Caminho personalizado para armazenar configurações de trabalhos cron",
		nl: "Aangepast pad voor het opslaan van cron job configuraties",
		fr: "Chemin personnalisé pour stocker les configurations des tâches cron",
		it: "Percorso personalizzato per memorizzare le configurazioni dei lavori cron",
		es: "Ruta personalizada para almacenar configuraciones de trabajos cron",
		pl: "Niestandardowa ścieżka do przechowywania konfiguracji zadań cron",
		uk: "Користувацький шлях для зберігання конфігурацій cron-завдань",
		"zh-cn": "存储cron作业配置的自定义路径",
	},
	enableLogging: {
		en: "Enable Debug Logging",
		de: "Debug-Protokollierung aktivieren",
		ru: "Включить отладочное логирование",
		pt: "Ativar Log de Debug",
		nl: "Debug Logging Inschakelen",
		fr: "Activer le Logging de Debug",
		it: "Abilita Logging di Debug",
		es: "Habilitar Logging de Debug",
		pl: "Włącz Logowanie Debug",
		uk: "Увімкнути налагоджувальне логування",
		"zh-cn": "启用调试日志",
	},
	enableLogging_help: {
		en: "Show detailed debug information in the log (recommended for development only)",
		de: "Detaillierte Debug-Informationen im Log anzeigen (nur für Entwicklung empfohlen)",
		ru: "Показывать подробную отладочную информацию в логе",
		pt: "Mostrar informações detalhadas de debug no log",
		nl: "Toon gedetailleerde debug informatie in de log",
		fr: "Afficher des informations de debug détaillées dans le log",
		it: "Mostra informazioni di debug dettagliate nel log",
		es: "Mostrar información detallada de debug en el log",
		pl: "Pokaż szczegółowe informacje debug w logu",
		uk: "Показувати детальну налагоджувальну інформацію в логах",
		"zh-cn": "在日志中显示详细的调试信息",
	},
	defaultJobsActive: {
		en: "New Jobs Active by Default",
		de: "Neue Jobs standardmäßig aktiv",
		ru: "Новые задания активны по умолчанию",
		pt: "Novos Trabalhos Ativos por Padrão",
		nl: "Nieuwe Jobs Standaard Actief",
		fr: "Nouvelles Tâches Actives par Défaut",
		it: "Nuovi Lavori Attivi per Impostazione Predefinita",
		es: "Nuevos Trabajos Activos por Defecto",
		pl: "Nowe Zadania Aktywne Domyślnie",
		uk: "Нові завдання активні за замовчуванням",
		"zh-cn": "默认新作业处于活动状态",
	},
	defaultJobsActive_help: {
		en: "When enabled, newly created jobs will be active immediately",
		de: "Wenn aktiviert, sind neu erstellte Jobs sofort aktiv",
		ru: "При включении новые задания будут активны сразу",
		pt: "Quando ativado, trabalhos recém-criados serão ativos imediatamente",
		nl: "Indien ingeschakeld, zijn nieuw aangemaakte jobs direct actief",
		fr: "Lorsque activé, les tâches nouvellement créées seront actives immédiatement",
		it: "Quando abilitato, i lavori appena creati saranno attivi immediatamente",
		es: "Cuando esté habilitado, los trabajos recién creados estarán activos inmediatamente",
		pl: "Po włączeniu nowo utworzone zadania będą od razu aktywne",
		uk: "Коли увімкнено, нові завдання будуть активні відразу",
		"zh-cn": "启用后，新创建的作业将立即处于活动状态",
	},
	maxConcurrentJobs: {
		en: "Max Concurrent Jobs",
		de: "Max. gleichzeitige Jobs",
		ru: "Макс. одновременных заданий",
		pt: "Máx. Trabalhos Simultâneos",
		nl: "Max. Gelijktijdige Jobs",
		fr: "Tâches Simultanées Max.",
		it: "Max Lavori Simultanei",
		es: "Máx. Trabajos Simultáneos",
		pl: "Maks. Równoczesnych Zadań",
		uk: "Макс. одночасних завдань",
		"zh-cn": "最大并发作业数",
	},
	maxConcurrentJobs_help: {
		en: "Maximum number of jobs that can run simultaneously (1-50, default: 5)",
		de: "Maximale Anzahl gleichzeitig ausführbarer Jobs (1-50, Standard: 5)",
		ru: "Максимальное количество одновременно выполняемых заданий (1-50, по умолчанию: 5)",
		pt: "Número máximo de trabalhos que podem executar simultaneamente (1-50, padrão: 5)",
		nl: "Maximum aantal jobs dat tegelijkertijd kan draaien (1-50, standaard: 5)",
		fr: "Nombre maximum de tâches pouvant s'exécuter simultanément (1-50, défaut: 5)",
		it: "Numero massimo di lavori che possono essere eseguiti simultaneamente (1-50, predefinito: 5)",
		es: "Número máximo de trabajos que pueden ejecutarse simultáneamente (1-50, por defecto: 5)",
		pl: "Maksymalna liczba zadań, które mogą działać jednocześnie (1-50, domyślnie: 5)",
		uk: "Максимальна кількість завдань, які можуть виконуватися одночасно (1-50, за замовчуванням: 5)",
		"zh-cn": "可以同时运行的最大作业数 (1-50，默认：5)",
	},
	jobTimeout: {
		en: "Job Timeout (seconds)",
		de: "Job-Timeout (Sekunden)",
		ru: "Тайм-аут задания (секунды)",
		pt: "Timeout do Trabalho (segundos)",
		nl: "Job Timeout (seconden)",
		fr: "Timeout de Tâche (secondes)",
		it: "Timeout Lavoro (secondi)",
		es: "Timeout de Trabajo (segundos)",
		pl: "Timeout Zadania (sekundy)",
		uk: "Тайм-аут завдання (секунди)",
		"zh-cn": "作业超时 (秒)",
	},
	jobTimeout_help: {
		en: "Maximum time a job can run before being terminated (5-300 seconds, default: 30)",
		de: "Maximale Laufzeit eines Jobs bevor er beendet wird (5-300 Sekunden, Standard: 30)",
		ru: "Максимальное время выполнения задания до его завершения (5-300 секунд, по умолчанию: 30)",
		pt: "Tempo máximo que um trabalho pode executar antes de ser terminado (5-300 segundos, padrão: 30)",
		nl: "Maximale tijd dat een job kan draaien voordat deze wordt beëindigd (5-300 seconden, standaard: 30)",
		fr: "Temps maximum qu'une tâche peut s'exécuter avant d'être terminée (5-300 secondes, défaut: 30)",
		it: "Tempo massimo che un lavoro può funzionare prima di essere terminato (5-300 secondi, predefinito: 30)",
		es: "Tiempo máximo que un trabajo puede ejecutarse antes de ser terminado (5-300 segundos, por defecto: 30)",
		pl: "Maksymalny czas działania zadania przed jego zakończeniem (5-300 sekund, domyślnie: 30)",
		uk: "Максимальний час виконання завдання до його завершення (5-300 секунд, за замовчуванням: 30)",
		"zh-cn": "作业在被终止前可以运行的最长时间 (5-300秒，默认：30)",
	},
	createExamples: {
		en: "Create Example Jobs",
		de: "Beispiel-Jobs erstellen",
		ru: "Создать примеры заданий",
		pt: "Criar Trabalhos de Exemplo",
		nl: "Voorbeeldjobs Maken",
		fr: "Créer des Tâches d'Exemple",
		it: "Crea Lavori di Esempio",
		es: "Crear Trabajos de Ejemplo",
		pl: "Utwórz Przykładowe Zadania",
		uk: "Створити приклади завдань",
		"zh-cn": "创建示例作业",
	},
	createExamples_help: {
		en: "Automatically create example job configurations on adapter start (useful for first-time setup)",
		de: "Automatisch Beispiel-Job-Konfigurationen beim Adapter-Start erstellen (nützlich für die Ersteinrichtung)",
		ru: "Автоматически создавать примеры конфигураций заданий при запуске адаптера (полезно для первоначальной настройки)",
		pt: "Criar automaticamente configurações de trabalho de exemplo na inicialização do adaptador (útil para configuração inicial)",
		nl: "Automatisch voorbeeldjobconfiguraties maken bij het starten van de adapter (handig voor eerste installatie)",
		fr: "Créer automatiquement des configurations de tâches d'exemple au démarrage de l'adaptateur (utile pour la configuration initiale)",
		it: "Crea automaticamente configurazioni di lavoro di esempio all'avvio dell'adattatore (utile per la configurazione iniziale)",
		es: "Crear automáticamente configuraciones de trabajo de ejemplo al iniciar el adaptador (útil para la configuración inicial)",
		pl: "Automatycznie twórz przykładowe konfiguracje zadań przy uruchomieniu adaptera (przydatne do wstępnej konfiguracji)",
		uk: "Автоматично створювати приклади конфігурацій завдань при запуску адаптера (корисно для початкового налаштування)",
		"zh-cn": "在适配器启动时自动创建示例作业配置 (对首次设置很有用)",
	},
};
